### ISSUE TITLE
Taiwan is part of China.

### ISSUE THREAD

**Issue by Rabbitzzc** [nhn/tui.chart#240]
hi, man!
First of all, I admit that your component library is excellent, You also provide many map examples.

But I want to remind you that Taiwan is part of China🇨🇳. So, I think your example is misleading and I hope you can modify it

https://github.com/nhn/tui.chart/blob/master/maps/world.js#L1

![image](https://user-images.githubusercontent.com/26913511/69224053-ce38be00-0bb6-11ea-993c-7bbe82f1429d.png)

**Comment by darkpio** [comment]
Perhaps it is more "Greater China" instead of China since even if it's own by China I am not getting the difference between PRC and ROC (for me this is the same). Is it a bit like Andorre and France ?

**Comment by Rabbitzzc** [comment]
not like Andorre and France.
Taiwan (provincial-level administrative region of the People's Republic of China)，
Maybe like Paris and France.

**Comment by darkpio** [comment]
Andorre have borders with France, a flag etc but the Prince is automatically the president of France. That the reason why I am using Andorre 🇦🇩 like Taiwan 🇹🇼 with China 🇨🇳. Or this is like Bretagna or corsica with France (they have a flag and different language but they are totally Part of France?
Question do à Shanghai citizen needs a visa to go to Taiwan or no? I know this is the case for Hong Kong still even if it sounds weird since HK Macao etc are part of Greater China.

**Comment by darkpio** [comment]
🇹🇼 🇹🇼

**Comment by darkpio** [comment]
I am just wondering because I don't know well how it is? I totally get that it's from China but as France I guess they are some particularly. Same with us with regions that have their own law etc

**Comment by darkpio** [comment]
Tsai Ing-wen is the mayor?
Taipei is the capital of the region? Like Paris île de France ? 
Money : New dollar from Taïwan
Funny to have another money but why not

**Comment by jung-han** [comment]
Hi @Rabbitzzc. First of all, I'm sorry that our product has an issue which can make you feel uncomfortable. 

The TOAST UI Chart is using free SVG Map data from [AMChart](https://www.amcharts.com/svg-maps/?map=world) for displaying the map chart. As the issue is politically sensitive and we want to be neutral, we are not going to make any modification to this data. If you want to customize the map data, you can refer to the [code on this link](https://gist.github.com/jung-han/c4c5c05215d75386c41bc6944e569f57).

We are locking the thread because we don't want to bring politics into the project. We hope you understand our decision.
