### ISSUE TITLE
New chart instance method which updates tooltip template

### ISSUE THREAD

**Issue by AlexDemian** [nhn/tui.chart#425]
Greetings!

I'm using Toast UI charts react wrapper.

I really like the feature that allows a custom chart tooltip template as a chart settings option, it's very useful; 
but I have faced with trouble: I can't update a tooltip template without creating a new chart instance. 
  
Can you provide a new Chart instance method (for example setTooltipTemplate()) that updates a tooltip template and re-renders the existing instance of the chart?

Or maybe is possible to handle custom labels in the chart data structure to display it instead of default x/y/r (that is the original issue which I tried to solve using a custom tooltip template)

![2](https://user-images.githubusercontent.com/27147054/97113237-a8366a80-16f1-11eb-963c-83e9d423323c.PNG)

Thank you in advance!

**Comment by jung-han** [comment]
@AlexDemian 

It seems to be a problem because there is no API to update when changing the current `options`. Probably, if development proceeds, options such as `setOptions` or `setTooltipTemplate` that you mentioned should come out. It is unlikely that we will be able to update it immediately because we are preparing the Chart 4 version, but this part is expected to be developed in the future due to many requests.

Thanks for the good comment!

**Comment by AlexDemian** [comment]
@jung-han 

setOptions() instance method which manually updates all options will be a great solution!

Thank you :)
