### ISSUE TITLE
An error occurs when click legend checkbox or legend text.

### ISSUE THREAD

**Issue by feents** [nhn/tui.chart#661]
**Describe the bug**
An error occurs when click legend checkbox or legend text.
My chart has a lot of series.
Perhaps this could be the cause.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/heuristic-meitner-t7i8e?file=/index.html'
2. Click on legend.
3. Works ok when "dummy_75" checkbox.
4. An error occurs when another checkbox.
5. An error occurs when click "dummy_75", "dummy_74" text.
6. An error occurs when another legend text.

**Expected behavior**
Works fine when click all checkbox, like click "dummy_75" checkbox.
Works fine when click all legend text.

**Screenshots**
![error_text_click](https://user-images.githubusercontent.com/67404954/116383608-f3246c80-a851-11eb-985f-1a30061e2b97.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 90.0.818.46

**Comment by jung-han** [comment]
As the width of the legend is specified, it seems that the legends that need to be stacked are not properly processed. In this case, there may be a problem in that not all of the legend items are drawn rather than the click event. Which action do you see as normal?

**Comment by feents** [comment]
> As the width of the legend is specified, it seems that the legends that need to be stacked are not properly processed. In this case, there may be a problem in that not all of the legend items are drawn rather than the click event. Which action do you see as normal?
I think, what if the legend scrolls?

**Comment by jung-han** [comment]
@feents 
I think scrolling is also a good way. Since it is a time-consuming task because it has to be separated by a separate canvas layer, the priority is slightly pushed back. Since we are developing a new chart, it will be difficult to develop it right now. If you are in a hurry, it is recommended to use the legend's ellipsis option to shorten it.
https://github.com/nhn/tui.chart/blob/main/docs/en/common-legend.md#options
