### ISSUE TITLE
programmatically changing series visibility

### ISSUE THREAD

**Issue by lorgan3** [nhn/tui.chart#663]
**Describe the bug**
Thank you for the cool library! For what I'm working on I would like to change the series visibility programmatically (so without the legend) but this doesn't currently work. As you can see in the example the legend gets unchecked but the line currently remains visible.

**To Reproduce**
1. Load https://codesandbox.io/s/kind-meitner-8700s?file=/src/index.js
2. Click the button below the chart
3. => The checkbox in the legend changes but the line is not hidden

**Expected behavior**
Updating the visibility prop changes the visibility of the series.

**Comment by jung-han** [comment]
@lorgan3 

This is because the visible option is written to be affected only when data is initially rendered. It seems to be necessary to consider the case of changing the visible option as setData or this way. We are currently preparing a new chart, so it will be difficult to immediately apply it. If you are in a hurry, it would be good if you decide the direction and make PR together.😃

**Comment by lorgan3** [comment]
Hi thanks for the response. I'm not really in a hurry, it's just a personal project and I'm working around it by remounting the chart every time I change the visibility.

I had a look at the code to see if I could do it but I couldn't quite figure out how to keep everything in sync yet. Also this might cause unwanted behavior for people who use `setData` and are currently setting the visibility attribute.
Maybe adding an api similar to `showSeriesDataLabel` and `hideSeriesDataLabel` makes more sense.

**Comment by jung-han** [comment]
@lorgan3 
Exactly! If it is added, not only the optional action but also the API addition must be done.
