### ISSUE TITLE
how to tooltip off

### ISSUE THREAD

**Issue by jncompany** [nhn/tui.chart#718]
i try...

```
tooltip: {
	visible: false,
}
```

not work..

**Comment by jwlee1108** [comment]
@jncompany 

> please keep the template when you open the issue.

Hello, it doesn't have a feature to hide the tooltip.
you can call a method `hideTooltip()` but I don't think it's the picture you want.

Using `template`, tooltips can be removed indirectly. but, it's not a perfect way.
```js
tooltip: {
  template: () => '',
},
```
I can't make it quickly because I have other tasks to do right now, but I'll try to make a tooltip-off option.

**Comment by jncompany** [comment]
thanks alot
